### ISSUE TITLE
deadbeef.h

### ISSUE THREAD

**Issue by noxxim** [barthez/deadbeef-gnome-mmkeys#3]
Hi.

You forgot to tell people (the not so experienced ones), they have to use the deadbeef.h from the players source. Maybe you want to add it to the Readme.

thanks
regards

**Comment by barthez** [comment]
Hi,

If you install deadbeef from package `deadbeef.h` is always provided. I've developed (it was more changing stuff) on ArchLinux where `deadbeef.h` was in `/usr/include/deadbeef/` directory and was included by default. In Ubuntu file goes to `/opt/deadbeef/` that's why it doesn't compile correctly.

Makefile have to updated to take into account deadbeef directory (guessed or user specified) while compilator is looking for header files. I encourage you to fork the project and solve this issue.

**Comment by noxxim** [comment]
Oh okay this was my fail. I don't remember that i installed the static linked standalone version in /opt. A symlink fixed it for me now.

**Comment by davidhealey** [comment]
I'm using the precompiled binary of deadbeef, where do I put deadbeef.h?
